name: video_editor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  ffmpeg_kit_flutter_new: ^3.2.0
  insta_assets_picker: ^3.3.0
  flutter:
    sdk: flutter
  path: ^1.9.0   
  path_provider: ^2.1.5
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   

flutter:
  uses-material-design: true
